#mysql -h localhost -p 1234 -u root

DROP DATABASE IF EXISTS SuperMarket;
CREATE DATABASE IF NOT EXISTS SuperMarket;
SHOW DATABASES ;
USE SuperMarket;

DROP TABLE IF EXISTS `Customer`;
CREATE TABLE IF NOT EXISTS `Customer`(
   CustID VARCHAR(6),
   CustTitle VARCHAR(5),
   CustName VARCHAR(30) NOT NULL DEFAULT 'Unknown',
   CustAddress VARCHAR(30),
   City VARCHAR(20),
   Province VARCHAR(20),
   PostalCode VARCHAR(9),
   CONSTRAINT PRIMARY KEY (CustID)
);
SHOW TABLES ;
DESCRIBE `Customer`;

DROP TABLE IF EXISTS `Orders`;
CREATE TABLE IF NOT EXISTS `Orders`(
   OrderID VARCHAR(6),
   OrderDate DATE,
   CustID VARCHAR(6),
   CONSTRAINT PRIMARY KEY (OrderID),
   CONSTRAINT FOREIGN KEY (CustID) REFERENCES `Customer`(CustID) ON DELETE CASCADE ON UPDATE CASCADE
);
SHOW TABLES ;
DESCRIBE `Orders`;

DROP TABLE IF EXISTS `Item`;
CREATE TABLE IF NOT EXISTS `Item`(
   ItemCode VARCHAR(6),
   Description VARCHAR(50),
   PackSize VARCHAR(20),
   UnitPrice DECIMAL(6,2),
   QtyOnHand INT(5),
   CONSTRAINT PRIMARY KEY (ItemCode)
);
SHOW TABLES ;
DESCRIBE `Item`;

DROP TABLE IF EXISTS `Order Detail`;
CREATE TABLE IF NOT EXISTS `Order Detail`(
   OrderID VARCHAR(6),
   ItemCode VARCHAR(6),
   OrderQTY INT(11),
   Discount DECIMAL(6,2),
   CONSTRAINT PRIMARY KEY (OrderID, ItemCode),
   CONSTRAINT FOREIGN KEY (OrderID) REFERENCES `Orders`(OrderID) ON DELETE CASCADE ON UPDATE CASCADE ,
   CONSTRAINT FOREIGN KEY (ItemCode) REFERENCES Item(ItemCode) ON DELETE CASCADE ON UPDATE CASCADE
);
SHOW TABLES ;
DESCRIBE `Order Detail`;
